#!/usr/bin/env bash
# Transfers a file from our client to server.
# Accepts four parameters:
# . 1 The path to the file to be transferred.
# . 2  The IP of the server to transfer the file to.
# . 3 The username that scp connects with.
# . 4 The path to the SSH private key that scp uses.

#checks if number of argument is less than 3
if [ $# -lt 4 ];
then
    #prints usage
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
 #   exit;
#fi;

#checks if number of argument is greater than or equal to 4
#if [ $# -eq 4 ];
#then
    #transfers file to server with strict host key checking disabled
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
#else
    #transfers file to server without ssh key
   # scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi;
