#!/usr/bin/env bash
# Install engineX
sudo apt-get install nginx -y
sudo sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
echo "Hello World!" > file.txt
sudo cp -r file.txt /var/www/html/index.html
rm file.txt
# sudo sed -i "s#server_name _;#server_name _; return 301 http://binarygecko.tech/redirect_me;#g" /etc/nginx/sites-enabled/default
sudo sed -i 's#server_name _;#&\n\tlocation /redirect_me {\n\t\treturn 301 http://binarygecko.tech/redirect_me;\n\t}#g' /etc/nginx/sites-enabled/default
sudo service nginx restart
