#!/usr/bin/env bash
# Script to configure HAProxy for server

# Install HAProxy
sudo apt update -y
# sudo apt-get install --no-install-recommends software-properties-common -y
# sudo add-apt-repository ppa:vbernat/haproxy-2.9 -y
# sudo apt-get install haproxy=2.9.* -y
sudo apt install haproxy -y

# Make a backup of the configuration file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
defaults
    mode http
    timeout client 15s
    timeout connect 10s
    timeout server 15s
    timeout http-request 10s

frontend http_server
    bind *:80
    default_backend http_runner

backend http_runner
    balance roundrobin
    server 470431-web-01 52.87.220.93:80 check
    server 470431-web-02 54.237.22.218:80 check
EOF

# Enable HAProxy
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

# Start HAProxy
sudo service haproxy start
