#!/usr/bin/env bash
# check if nginx is installed
# Re-Configures an Nginx server to listen on port 80

Check=$(which nginx)
if [ -z "$Check" ]
then
	echo "=== Installing Nginx ==="
	sudo apt update -y
	apt -y install nginx
	echo "+++++++++++++++++++++++++"
	echo "++++ Nginx Installed ++++"
	echo "+++++++++++++++++++++++++"
else
	echo "$Check is Installed Already"
fi

# Set nginx to listen at port 80
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

# start Nginx
sudo service nginx restart
