#!/usr/bin/env bash

# Install Uncomplicated FireWall (UFW) and configure basic firewall rules

sudo apt-get -y update
sudo apt-get -y upgrade

# Install UFW
sudo apt-get -y install ufw

# Allow incoming SSH connections (port 22)
sudo ufw allow 22

# Allow incoming traffic on ports 443 (HTTPS) and 80 (HTTP)
sudo ufw allow 443
sudo ufw allow 80

# Set incoming traffic to deny
sudo ufw default deny incoming

# Set outgoing traffic to allow
sudo ufw default allow outgoing

# Add NAT rule to redirect port 8080/TCP to port 80/TCP
sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80

# Enable UFW
sudo ufw enable

